### ISSUE TITLE
Use nuget package instead

### ISSUE THREAD

**Issue by CaledoniaProject** [CCob/SweetPotato#6]
Can't compile NtApiDotNet with VS2019. So I removed the sub project and installed NtApiDotNet from nuget, and it compiles now.

Can you update the project?

**Comment by CCob** [comment]
What problem do you have compiling?  My environment is also 2019 and it works fine.  The reason it's like this currently and it also uses Fody to compress and package NtApiDotNet inside the main executable so there are no dependencies and it's under 1MB for Cobalt Strike.

**Comment by CaledoniaProject** [comment]
Weird, it compiled this time.

I got a few CS0618 warnings about FILETIME structure though, it prompts me to use System.Runtime.InteropServices.ComTypes.FILETIME instead.
